### ISSUE TITLE
roles of to and from in the config file

### ISSUE THREAD

**Issue by mreichstadt** [mremi/ContactBundle#31]
Hi,
I don't manage to make it work on my website, I configured correctly the smtp for our company, and then I looked at the config. What do the "to" and "from" represent? I mean I understand the "from" which should lead to the sender (the webmaster), but what does the "to" leaves to?

Thank you very much in advance,
Matthieu

**Comment by mremi** [comment]
Hi,

These 2 config are used when the form is properly filled in order to send an email.
So the `from` represents the sender which is optional. By default, the form data are used.
The `to` is mandatory and should contain info about someone of your company (or anyone able to process the demand).

You can see the usage here: https://github.com/mremi/ContactBundle/blob/master/Mailer/TwigSwiftMailer.php#L81

And how to configure it: https://github.com/mremi/ContactBundle#step-4-configure-the-mremicontactbundle . Note the `name` is optional.
