### ISSUE TITLE
Extends the bundle for remove unwanted fields and add new ones

### ISSUE THREAD

**Issue by reypm** [mremi/ContactBundle#6]
It's possible to remove fields like for example title and add new ones like phone and company? How I do that and where? In `ContactType.php`?

**Comment by numerogeek** [comment]
Hi @mremi ,

This issue is itself a great doc, but it miss a point : I'd like to remove the title field, but I have activated the database storage.
Currently, and following this step-by-step tutorial, I finally have a doctrine error sayin that de title field can't be null ( Constraint violation..)
In your xml, nothin is specified, so it's required by default. Do you  have an idea about how to override the mapping ? 

Thx !

**Comment by mremi** [comment]
Hi @numerogeek ,

The mapping file should be updated with `nullable="true"` for all fields except `createdAt`. Thus, all the use cases will be covered.
Do you want to do it?
